'use strict';
const EMP=[
['سارة أحمد',97.8,'3:05',98,94,91,96,93],['ريم محمد',94.6,'3:18',97,91,89,94,91],['نورة خالد',91.3,'3:26',96,88,87,92,89],['جود عبدالله',88.7,'3:31',95,85,84,90,87],['هند علي',84.2,'3:42',94,81,82,87,84],['لطيفة سالم',79.5,'3:58',92,78,79,83,80],['مشاعل حسن',74.1,'4:10',90,73,75,79,76],['أمل يوسف',68.9,'4:25',88,69,70,75,71],['رغد إبراهيم',61.7,'4:46',85,62,65,68,64],['شهد ماجد',53.4,'5:02',81,54,57,61,58]
].map((x,i)=>({id:i+1,name:x[0],score:x[1],aht:x[2],abs:x[3],quality:x[4],util:x[5],csat:x[6],fcr:x[7]}));
const SUPS={
  عهد:{name:'عهد',teams:[['الفريق 1','وجدان',14],['الفريق 2','نورة',12],['الفريق 3','ريم',14],['الفريق 4','مها',13]]},
  رهف:{name:'رهف',teams:[['الفريق 5','لينا',13],['الفريق 6','هدى',12],['الفريق 7','جود',14],['الفريق 8','دلال',14]]}
};
const MONTHS=['أبريل 2025','مايو 2025','يونيو 2025'];
function status(v){return v>=90?'ممتاز':v>=80?'جيد':'منخفض'}
function cls(v){return v>=90?'excellent':v>=80?'good':'low'}
function metricColor(v){return v>=90?'green':v>=80?'amber':'red'}
function ahtGood(v){return v<='3:30'}
function trend(v,dir='up'){return '<span class="trend '+(dir==='down'?'down':'up')+'">'+(dir==='down'?'↓':'↑')+' '+v+'</span>'}
function metricCard(name,value,sub,good=true,direction='up'){return '<div class="metric-card '+(good?'ok':'bad')+'"><div class="metric-title">'+name+'</div><div class="metric-value">'+value+'</div><div class="metric-sub">'+sub+' '+trend(direction==='down'?'2%':'3%',direction)+'</div></div>'}
function menu(role){const home=role==='manager'?'manager.html':role==='super'?'super.html':role==='supervisor'?'supervisor.html':'employee-home.html';return `<div id="drawer" class="drawer"><div class="drawer-head"><b>منصة أداء</b><button id="closeDrawer" class="iconbtn">×</button></div><a href="${home}">⌂ الرئيسية</a><a href="${home}#structure">⌘ هيكل المشروع</a><a href="${home}#performance">▥ مجمل الأداء</a><a href="reports-${role}.html">▤ التقارير — آخر 3 أشهر</a><a href="${role==='employee'?'employee-kpi.html':home+'#teams'}">👥 الأداء والفرق</a><a href="${role==='employee'?'employee-monthly.html':home+'#notes'}">♡ الملاحظات وخطط التطوير</a><a href="${role==='employee'?'employee-side-by-side.html':home+'#sessions'}">◷ الجلسات والمواعيد</a><a href="${role==='employee'?'employee-report.html':('team-report.html')}">🖨 طباعة التقرير</a><a href="index.html">↪ تسجيل الخروج</a></div><div id="overlay" class="overlay"></div>`}
function header(role,name){return `<header class="topbar"><button id="hamb" class="hamb" aria-label="القائمة"><i></i><i></i><i></i></button><div class="topbrand"><b>أداء</b><span>Aadaa</span></div><div class="search">⌕ <input placeholder="البحث عن موظفة، فريق، أو مؤشر ..."></div><div class="topuser"><div><b>${name}</b><small>${role==='manager'?'مدير المشروع':role==='super'?'سوبر':role==='supervisor'?'مشرفة':'موظفة'}</small></div><div class="avatar">${name[0]}</div><span class="bell">♧</span></div></header>`}
function shell(content,role,name,title){document.body.innerHTML=header(role,name)+menu(role)+`<div class="app"><main class="content"><div class="page-title"><div><h1>${title}</h1><p>لوحة تحكم منظمة لمتابعة الأداء واتخاذ القرار بسرعة.</p></div><select><option>آخر 3 أشهر</option><option>يونيو 2025</option></select></div>${content}<footer>منصة أداء • متابعة • تطوير • إنجاز</footer></main></div>`;bindMenu()}
function bindMenu(){const d=document.getElementById('drawer'),o=document.getElementById('overlay'),h=document.getElementById('hamb');if(!h)return;h.onclick=()=>{d.classList.add('open');o.classList.add('show')};document.getElementById('closeDrawer').onclick=()=>{d.classList.remove('open');o.classList.remove('show')};o.onclick=()=>{d.classList.remove('open');o.classList.remove('show')}}
function structure(){let html='<div class="structure" id="structure"><div class="org root"><b>شهد</b><small>مدير المشروع • 106 موظفات</small></div><div class="orgline"></div><div class="supgrid">';for(const key of ['رهف','عهد']){const s=SUPS[key];html+=`<div class="supblock"><div class="org sup"><b>سوبر ${s.name}</b><small>53 موظفة • 4 مشرفات</small></div><div class="teams">`;s.teams.forEach(t=>html+=`<div class="team"><b>${t[0]}</b><span>مشرفة ${t[1]}</span><small>${t[2]} موظفة</small></div>`);html+='</div></div>'}return html+'</div></div>'}
function kpis(){return `<section id="performance" class="section"><div class="section-head"><h2>مجمل أداء الفريق العام</h2><span class="filter">آخر 3 أشهر ▾</span></div><div class="metrics">${metricCard('SL','92%','مستوى الخدمة',true)}${metricCard('NPS','88%','رضا العميل',true)}${metricCard('FCR','85%','من أول مكالمة',true)}${metricCard('AHT','3:28','متوسط وقت المكالمة',true,'down')}${metricCard('Quality','90%','الجودة',true)}${metricCard('C-SAT','92%','رضا العميل عن الخدمة',true)}${metricCard('Utilization','87%','الإنتاجية',true)}${metricCard('Absenteeism','5%','الغياب',false,'down')}</div></section>`}
function charts(){return `<div class="chartgrid"><div class="panel"><div class="section-head"><h3>اتجاه الأداء العام (آخر 3 أشهر)</h3><span class="muted">أبريل → يونيو</span></div><div class="linechart"><div class="line l1"></div><div class="line l2"></div><div class="line l3"></div><div class="axis"><span>أبريل</span><span>مايو</span><span>يونيو</span></div></div><div class="legend"><span>● Quality</span><span>● C-SAT</span><span>● FCR</span><span>● SL</span></div></div><div class="panel"><div class="section-head"><h3>توزيع الموظفات حسب الفريق</h3></div><div class="bars">${[14,12,14,13,13,12,14,14].map((n,i)=>`<div><b>${n}</b><i style="height:${n*7}px"></i><small>ف${i+1}</small></div>`).join('')}</div></div><div class="panel insights"><div class="section-head"><h3>أهم المؤشرات</h3></div><p class="insight good">🟢 أعلى جودة <b>95%</b> — الفريق 3</p><p class="insight good">🟢 أفضل التزام <b>96%</b> — الفريق 2</p><p class="insight bad">🔴 أعلى AHT <b>3:45</b> — الفريق 6</p><p class="insight bad">🔴 انخفاض FCR <b>80%</b> — الفريق 2</p></div></div>`}
function teamTable(teams=[...SUPS.رهف.teams,...SUPS.عهد.teams]){let rows=[];teams.forEach((t,i)=>{const q=[92,90,94,89,91,86,93,88][i%8],cs=[94,91,95,89,92,87,93,90][i%8],f=[88,85,89,84,86,81,90,83][i%8],a=['3:20','3:32','3:18','3:40','3:25','3:45','3:22','3:35'][i%8];rows.push(`<tr><td>${t[0]}</td><td>${t[1]}</td><td>${t[2]}</td><td class="${metricColor(q)}">${q}%</td><td class="${metricColor(cs)}">${cs}%</td><td class="${metricColor(f)}">${f}%</td><td class="${ahtGood(a)?'green':'red'}">${a}</td><td class="${metricColor([89,83,91][i%3])}">${[89,83,91][i%3]}%</td></tr>`)});return `<section id="teams" class="panel tablepanel"><div class="section-head"><h2>مقارنة أداء الفرق — آخر 3 أشهر</h2><button class="smallbtn" onclick="window.print()">طباعة التقرير</button></div><div class="tablewrap"><table><thead><tr><th>الفريق</th><th>المشرفة</th><th>الموظفات</th><th>Quality</th><th>C-SAT</th><th>FCR</th><th>AHT</th><th>Utilization</th></tr></thead><tbody>${rows.join('')}</tbody><tfoot><tr><th>الإجمالي</th><th>8 مشرفات</th><th>106</th><th class="green">90%</th><th class="green">91%</th><th class="amber">85%</th><th class="green">3:28</th><th class="green">87%</th></tr></tfoot></table></div></section>`}
function notes(){return `<div id="notes" class="lower"><div class="panel"><div class="section-head"><h3>أبرز الملاحظات التطويرية</h3><span class="link">عرض الكل</span></div><p class="notice red">انخفاض FCR في الفريق 2 <small>منذ 3 أيام</small></p><p class="notice green">تحسن مستوى الجودة في الفريق 4 <small>منذ 4 أيام</small></p><p class="notice red">ارتفاع وقت المكالمة في الفريق 6 <small>منذ أسبوع</small></p></div><div class="panel" id="sessions"><div class="section-head"><h3>الجلسات القادمة</h3><button class="smallbtn" onclick="scheduleSession()">+ تحديد موعد جلسة</button></div><p>◷ Coaching — مراجعة حالة حرجة</p><p>◷ Side by Side — الاستماع لمكالمة وتقديم تغذية راجعة</p><p class="muted">يمكن تحديد الموعد وتحديثه ثم طباعته ضمن التقرير.</p></div></div>`}
function scheduleSession(){const d=prompt('أدخل موعد الجلسة (مثال: 20 يونيو 2025 - 10:00 صباحًا)');if(d){localStorage.setItem('adaa_session',d);alert('تم حفظ موعد الجلسة: '+d);location.reload()}}
function managerHome(){shell(`<div class="hero"><div><h2>مرحبًا شهد 👋</h2><p>نظرة شاملة على أداء المشروع والفرق التابعة.</p></div><div class="heroquote">«معًا نصنع تجربة أداء أفضل»</div></div><div class="summary"><div><span>إجمالي الموظفات</span><b>106</b></div><div><span>عدد السوبر</span><b>2</b></div><div><span>عدد المشرفات</span><b>8</b></div><div><span>عدد الفرق</span><b>8</b></div></div>${structure()}${kpis()}${charts()}${teamTable()}${notes()}`,'manager','شهد','إدارة المشروع')}
function superHome(){const s=SUPS.عهد;let teamCards=s.teams.map(t=>`<div class="teamcard"><b>${t[0]}</b><span>مشرفة ${t[1]}</span><strong>${t[2]} موظفة</strong><a href="#performance">فتح أداء الفريق</a></div>`).join('');shell(`<div class="hero"><div><h2>مرحبًا عهد 👋</h2><p>لوحة السوبر — متابعة 4 فرق و53 موظفة من مكان واحد.</p></div><div class="heroquote">«متابعة أسرع • قرارات أوضح»</div></div><div class="summary"><div><span>إجمالي الموظفات</span><b>53</b></div><div><span>عدد المشرفات</span><b>4</b></div><div><span>عدد الفرق</span><b>4</b></div><div><span>متوسط الأداء</span><b class="green">89%</b></div></div><section class="panel"><div class="section-head"><h2>الفرق التابعة</h2><span class="filter">4 فرق</span></div><div class="teamcards">${teamCards}</div></section>${kpis()}${charts()}${teamTable(s.teams)}${notes()}`,'super','عهد','لوحة السوبر عهد')}
function supervisorHome(){const teams=[['الفريق 1','وجدان',14]];shell(`<div class="hero"><div><h2>مرحبًا وجدان 👋</h2><p>لوحتك الخاصة كمشرفة — متابعة فريقك وموظفاتك.</p></div><div class="heroquote">«ملاحظة اليوم تصنع تحسن الغد»</div></div><div class="summary"><div><span>موظفات الفريق</span><b>14</b></div><div><span>متوسط الأداء</span><b class="green">90%</b></div><div><span>جلسات هذا الشهر</span><b>6</b></div><div><span>حالات تحتاج متابعة</span><b class="red">2</b></div></div>${kpis()}${charts()}${teamTable(teams)}${notes()}<section class="panel"><div class="section-head"><h3>موظفات الفريق</h3><button class="smallbtn" onclick="window.print()">طباعة تقرير الفريق</button></div><div class="employeechips">${EMP.slice(0,7).map(e=>`<span>${e.name} <b class="${cls(e.score)}">${e.score}%</b></span>`).join('')}</div></section>`,'supervisor','وجدان','لوحة المشرفة وجدان')}
function employeeHome(){const e=EMP[0];document.body.innerHTML=header('employee','سارة أحمد')+menu('employee')+`<div class="app"><main class="content"><div class="page-title"><div><h1>مرحبًا سارة أحمد 👋</h1><p>مساحتك الشخصية لمتابعة أدائك وتطورك.</p></div><span class="pill excellent">أداء ممتاز</span></div><div class="summary"><div><span>أدائي الحالي</span><b class="green">${e.score}%</b></div><div><span>Quality</span><b class="green">${e.quality}%</b></div><div><span>C-SAT</span><b class="green">${e.csat}%</b></div><div><span>FCR</span><b class="green">${e.fcr}%</b></div></div><section id="performance" class="section"><div class="section-head"><h2>مؤشرات أدائي</h2><span class="filter">آخر 3 أشهر</span></div><div class="metrics">${metricCard('AHT',e.aht,'الهدف 3:30',ahtGood(e.aht),'down')}${metricCard('Absenteeism',e.abs+'%','الهدف 95%',e.abs>=95)}${metricCard('Quality',e.quality+'%','الهدف 80%',e.quality>=80)}${metricCard('Utilization',e.util+'%','الهدف 85%',e.util>=85)}${metricCard('C-SAT',e.csat+'%','رضا العميل',e.csat>=90)}${metricCard('FCR',e.fcr+'%','من أول مكالمة',e.fcr>=90)}</div></section><div id="monthly" class="lower"><div class="panel"><h3>نقاط القوة</h3><p>أداء متميز في الجودة ورضا العميل وخدمة العميل من أول مكالمة.</p></div><div class="panel"><h3>فرص التحسين</h3><p>المحافظة على النتائج ومتابعة أي تغير في المؤشرات شهريًا.</p></div></div><div id="sessions" class="panel"><div class="section-head"><h3>الجلسات والمواعيد</h3><button class="smallbtn" onclick="scheduleSession()">تحديد موعد الجلسة</button></div><p>Coaching و Side by Side تظهر هنا مع الموعد والملاحظات.</p><p class="muted">الموعد المحفوظ: ${localStorage.getItem('adaa_session')||'لم يتم تحديد موعد بعد'}</p></div><section class="panel"><div class="section-head"><h3>تقرير أدائي</h3><button class="btn" onclick="window.print()">طباعة التقرير</button></div><p>يشمل مؤشرات الأداء، الملاحظات التطويرية، والجلسات لآخر 3 أشهر.</p></section><footer>منصة أداء • ملف الموظفة سارة أحمد</footer></main></div>`;bindMenu()}
function reports(role){const cfg={manager:['شهد','تقرير شامل للمشروع وجميع السوبر والمشرفات والفرق.'],super:['عهد','تقرير شامل للفرق التابعة للسوبر عهد.'],supervisor:['وجدان','تقرير فريق وجدان والموظفات التابعة لها.']};const [name,desc]=cfg[role]||cfg.supervisor;let teams=role==='manager'?[...SUPS.رهف.teams,...SUPS.عهد.teams]:role==='super'?SUPS.عهد.teams:[['الفريق 1','وجدان',14]];let rows=teams.map((t,i)=>`<tr><td>${t[0]}</td><td>${t[1]}</td><td>${t[2]}</td><td class="green">يونيو: ${[92,90,94,89,91,86,93,88][i%8]}%</td><td class="amber">مايو: ${[90,88,92,87,90,84,91,86][i%8]}%</td><td class="green">أبريل: ${[88,86,90,85,88,82,89,84][i%8]}%</td><td><span class="pill ${i===5?'low':'excellent'}">${i===5?'يحتاج متابعة':'مستقر'}</span></td></tr>`).join('');shell(`<div class="hero"><div><h2>تقارير الأداء — آخر 3 أشهر</h2><p>${desc}</p></div><button class="btn" onclick="window.print()">🖨 طباعة التقرير</button></div><div class="reportcards"><div><b>أبريل</b><span>87%</span></div><div><b>مايو</b><span>89%</span></div><div><b>يونيو</b><span>91%</span></div></div><section class="panel tablepanel"><div class="section-head"><h2>المقارنة الشهرية</h2><span>SL • NPS • Quality • C-SAT • FCR • AHT • Utilization • Absenteeism</span></div><div class="tablewrap"><table><thead><tr><th>الفريق</th><th>المشرفة</th><th>الموظفات</th><th>يونيو</th><th>مايو</th><th>أبريل</th><th>الحالة</th></tr></thead><tbody>${rows}</tbody></table></div></section>` ,role,name,'التقارير')}
function login(){document.body.innerHTML=`<div class="loginPage"><div class="loginCard"><div class="logoBig">أداء <span>Aadaa</span></div><h1>منصة أداء</h1><p>متابعة • تطوير • إنجاز</p><label>نوع الحساب</label><select id="role"><option value="manager">مدير المشروع — شهد</option><option value="super">سوبر — عهد</option><option value="supervisor">مشرفة — وجدان</option><option value="employee">موظفة — سارة أحمد</option></select><button class="btn" id="go">تسجيل الدخول</button></div></div>`;document.getElementById('go').onclick=()=>{const r=document.getElementById('role').value;location.href=r==='manager'?'manager.html':r==='super'?'super.html':r==='supervisor'?'supervisor.html':'employee-home.html'}}
function route(){const p=location.pathname.split('/').pop()||'index.html';if(p==='manager.html')managerHome();else if(p==='super.html')superHome();else if(p==='supervisor.html')supervisorHome();else if(p==='reports-manager.html')reports('manager');else if(p==='reports-super.html')reports('super');else if(p==='reports-supervisor.html')reports('supervisor');else if(p==='employee-home.html')employeeHome();else if(p==='index.html'||p==='')login();else login()}
document.addEventListener('DOMContentLoaded',route);
