'use strict';
const EMP=[['سارة أحمد',97.8,'3:05',98,94,91,96,93],['ريم محمد',94.6,'3:18',97,91,89,94,91],['نورة خالد',91.3,'3:26',96,88,87,92,89],['جود عبدالله',88.7,'3:31',95,85,84,90,87],['هند علي',84.2,'3:42',94,81,82,87,84],['لطيفة سالم',79.5,'3:58',92,78,79,83,80],['مشاعل حسن',74.1,'4:10',90,73,75,79,76],['أمل يوسف',68.9,'4:25',88,69,70,75,71],['رغد إبراهيم',61.7,'4:46',85,62,65,68,64],['شهد ماجد',53.4,'5:02',81,54,57,61,58]].map((x,i)=>({id:i+1,name:x[0],score:x[1],aht:x[2],abs:x[3],quality:x[4],util:x[5],csat:x[6],fcr:x[7]}));
const SUPS={عهد:{name:'عهد',total:53,teams:[['الفريق 1','وجدان',14],['الفريق 2','نورة',12],['الفريق 3','ريم',14],['الفريق 4','مها',13]]},رهف:{name:'رهف',total:53,teams:[['الفريق 5','لينا',13],['الفريق 6','هدى',12],['الفريق 7','جود',14],['الفريق 8','دلال',13]]}};
const ALLTEAMS=[...SUPS.عهد.teams,...SUPS.رهف.teams];
const PERIODS=['أسبوعي','شهري','ربع سنوي','سنوي'];
const PERIOD_DATA={
 'أسبوعي':{score:91,SL:94,NPS:90,FCR:87,AHT:'3:24',Quality:92,CSAT:94,Utilization:89,Absenteeism:3, trend:'+2.4%', label:'هذا الأسبوع'},
 'شهري':{score:89,SL:92,NPS:88,FCR:85,AHT:'3:28',Quality:90,CSAT:92,Utilization:87,Absenteeism:5, trend:'+1.8%', label:'هذا الشهر'},
 'ربع سنوي':{score:91,SL:93,NPS:91,FCR:88,AHT:'3:25',Quality:92,CSAT:93,Utilization:88,Absenteeism:4, trend:'+3.1%', label:'آخر 3 أشهر'},
 'سنوي':{score:87,SL:91,NPS:86,FCR:83,AHT:'3:31',Quality:88,CSAT:90,Utilization:85,Absenteeism:6, trend:'+0.9%', label:'هذا العام'}
};
const REPORT_DATA={
 'أسبوعي':[88,90,92,87,91,85,89,86],
 'شهري':[92,90,94,89,91,86,93,88],
 'ربع سنوي':[94,92,96,91,93,89,95,90],
 'سنوي':[89,87,91,86,90,84,92,85]
};
function status(v){return v>=90?'ممتاز':v>=80?'جيد':'منخفض'}
function cls(v){return v>=90?'excellent':v>=80?'good':'low'}
function metricColor(v){return v>=90?'green':v>=80?'amber':'red'}
function ahtGood(v){return v<='3:30'}
function trend(v,dir='up'){return '<span class="trend '+(dir==='down'?'down':'up')+'">'+(dir==='down'?'↓':'↑')+' '+v+'</span>'}
function metricCard(name,value,sub,good=true,direction='up'){return '<div class="metric-card '+(good?'ok':'bad')+'"><div class="metric-title">'+name+'</div><div class="metric-value">'+value+'</div><div class="metric-sub">'+sub+' '+trend(direction==='down'?'2%':'3%',direction)+'</div></div>'}
function menu(role){const home=role==='manager'?'manager.html':role==='super'?'super.html':role==='supervisor'?'supervisor.html':'employee-home.html';const report=role==='manager'?'reports-manager.html':role==='super'?'reports-super.html':role==='supervisor'?'reports-supervisor.html':'employee-report.html';return `<div id="drawer" class="drawer"><div class="drawer-head"><b>منصة أداء</b><button id="closeDrawer" class="iconbtn">×</button></div><div class="drawer-user">${role==='manager'?'شهد — مدير المشروع':role==='super'?'عهد — سوبر':role==='supervisor'?'وجدان — مشرفة':'سارة أحمد — موظفة'}</div><a href="${home}">⌂ الرئيسية</a><a href="${home}#structure">⌘ هيكل المشروع</a><a href="${home}#performance">▥ مجمل الأداء</a><a href="${report}">▤ التقارير</a><a href="${home}#teams">👥 الفرق والموظفات</a><a href="${home}#notes">♡ الملاحظات والتطوير</a><a href="${home}#sessions">◷ الجلسات والمواعيد</a><a href="${role==='employee'?'employee-report.html':'team-report.html'}">🖨 طباعة التقرير</a><a href="index.html">↪ تسجيل الخروج</a></div><div id="overlay" class="overlay"></div>`}
function header(role,name){return `<header class="topbar"><button id="hamb" class="hamb" aria-label="القائمة"><i></i><i></i><i></i></button><div class="topbrand"><b>أداء</b><span>Aadaa</span></div><div class="search">⌕ <input placeholder="البحث عن موظفة، فريق، أو مؤشر ..."></div><div class="topuser"><div><b>${name}</b><small>${role==='manager'?'مدير المشروع':role==='super'?'سوبر':role==='supervisor'?'مشرفة':'موظفة'}</small></div><div class="avatar">${name[0]}</div><span class="bell">♧</span></div></header>`}
function shell(content,role,name,title){document.body.innerHTML=header(role,name)+menu(role)+`<div class="app"><main class="content"><div class="page-title"><div><h1>${title}</h1><p>لوحة مؤسسية موحدة لمتابعة الأداء واتخاذ القرار.</p></div><div class="period-switch">${PERIODS.map((p,i)=>`<button class="period ${i===1?'active':''}" data-period="${p}">${p}</button>`).join('')}</div></div>${content}<footer>منصة أداء • متابعة • تطوير • إنجاز</footer></main></div>`;bindMenu();bindPeriods()}
function bindMenu(){const d=document.getElementById('drawer'),o=document.getElementById('overlay'),h=document.getElementById('hamb');if(!h)return;h.onclick=()=>{d.classList.add('open');o.classList.add('show')};document.getElementById('closeDrawer').onclick=()=>{d.classList.remove('open');o.classList.remove('show')};o.onclick=()=>{d.classList.remove('open');o.classList.remove('show')}}
function bindPeriods(){document.querySelectorAll('.period').forEach(b=>b.onclick=()=>{document.querySelectorAll('.period').forEach(x=>x.classList.remove('active'));b.classList.add('active');const period=b.dataset.period;document.querySelectorAll('.selected-period').forEach(label=>label.textContent=period);applyPeriodData(period)})}
function applyPeriodData(period){
 const d=PERIOD_DATA[period]||PERIOD_DATA['شهري'];
 document.querySelectorAll('[data-kpi]').forEach(el=>{const key=el.dataset.kpi;if(d[key]!==undefined)el.textContent=(key==='Absenteeism'?d[key]+'%':d[key]+(typeof d[key]==='number'?'%':''));});
 document.querySelectorAll('[data-report-score]').forEach(el=>{const i=Number(el.dataset.reportScore);if(REPORT_DATA[period]&&REPORT_DATA[period][i]!==undefined)el.textContent=REPORT_DATA[period][i]+'%';});
 document.querySelectorAll('[data-period-label]').forEach(el=>el.textContent=d.label);
}

function periodBar(){return `<div class="periodbar"><span>عرض الأداء حسب الفترة:</span>${PERIODS.map((p,i)=>`<button class="period ${i===1?'active':''}" data-period="${p}">${p}</button>`).join('')}<b class="selected-period">شهري</b></div>`}
function structure(){return `<section class="structure" id="structure"><div class="section-head"><h2>هيكل المشروع</h2><span class="muted">106 موظفة • 2 سوبر • 8 مشرفات • 8 فرق</span></div><div class="org root"><b>شهد</b><small>مدير المشروع • 106 موظفات</small></div><div class="orgline"></div><div class="supgrid">${['عهد','رهف'].map(key=>{const s=SUPS[key];return `<div class="supblock"><div class="org sup"><b>سوبر ${s.name}</b><small>${s.total} موظفة • 4 مشرفات</small></div><div class="teams">${s.teams.map(t=>`<a class="team" href="${key==='عهد'&&t[1]==='وجدان'?'supervisor.html':'#'}"><b>${t[0]}</b><span>مشرفة ${t[1]}</span><small>${t[2]} موظفة</small></a>`).join('')}</div></div>`}).join('')}</div></section>`}
function kpis(scope='project'){const d=PERIOD_DATA['شهري'];return `<section id="performance" class="section"><div class="section-head"><h2>مجمل الأداء العام ${scope==='project'?'للمشروع':''}</h2><span class="filter selected-period">شهري</span></div><div class="metrics">${metricCard('SL',`<span data-kpi="SL">${d.SL}%</span>`,'مستوى الخدمة',true)}${metricCard('NPS',`<span data-kpi="NPS">${d.NPS}%</span>`,'رضا العميل',true)}${metricCard('FCR',`<span data-kpi="FCR">${d.FCR}%</span>`,'من أول مكالمة',true)}${metricCard('AHT',`<span data-kpi="AHT">${d.AHT}</span>`,'متوسط وقت المكالمة',true,'down')}${metricCard('Quality',`<span data-kpi="Quality">${d.Quality}%</span>`,'الجودة',true)}${metricCard('C-SAT',`<span data-kpi="CSAT">${d.CSAT}%</span>`,'رضا العميل',true)}${metricCard('Utilization',`<span data-kpi="Utilization">${d.Utilization}%</span>`,'الإنتاجية',true)}${metricCard('Absenteeism',`<span data-kpi="Absenteeism">${d.Absenteeism}%</span>`,'الغياب',false,'down')}</div><div class="period-note">البيانات المعروضة تتغير حسب الفترة المختارة وتشمل نتائج الفترة نفسها.</div></section>`}

function charts(){return `<div class="chartgrid"><div class="panel"><div class="section-head"><h3>اتجاه الأداء</h3><span class="muted">آخر 3 أشهر</span></div><div class="linechart"><div class="line l1"></div><div class="line l2"></div><div class="line l3"></div><div class="axis"><span>الشهر الأول</span><span>الشهر الثاني</span><span>الشهر الثالث</span></div></div><div class="legend"><span>● Quality</span><span>● C-SAT</span><span>● FCR</span><span>● SL</span></div></div><div class="panel"><div class="section-head"><h3>توزيع الموظفات</h3></div><div class="bars">${ALLTEAMS.map((t,i)=>`<div><b>${t[2]}</b><i style="height:${t[2]*7}px"></i><small>${i+1}</small></div>`).join('')}</div></div><div class="panel insights"><div class="section-head"><h3>أهم التنبيهات</h3></div><p class="insight good">🟢 تحسن الجودة <b>+4%</b></p><p class="insight good">🟢 تحسن الالتزام <b>+3%</b></p><p class="insight bad">🔴 ارتفاع AHT في الفريق 6</p><p class="insight bad">🔴 انخفاض FCR في الفريق 2</p></div></div>`}
function teamTable(teams=ALLTEAMS){const qs=[92,90,94,89,91,86,93,88],cs=[94,91,95,89,92,87,93,90],fs=[88,85,89,84,86,81,90,83],us=[89,83,91,86,88,79,92,84];const rows=teams.map((t,i)=>{const q=qs[i%8],c=cs[i%8],f=fs[i%8],u=us[i%8],a=['3:20','3:32','3:18','3:40','3:25','3:45','3:22','3:35'][i%8];return `<tr><td><a class="rowlink" href="#">${t[0]}</a></td><td>${t[1]}</td><td>${t[2]}</td><td class="${metricColor(q)}">${q}%</td><td class="${metricColor(c)}">${c}%</td><td class="${metricColor(f)}">${f}%</td><td class="${ahtGood(a)?'green':'red'}">${a}</td><td class="${metricColor(u)}">${u}%</td></tr>`}).join('');return `<section id="teams" class="panel tablepanel"><div class="section-head"><h2>أداء الفرق بشكل مستقل</h2><button class="smallbtn" onclick="window.print()">طباعة التقرير</button></div><div class="tablewrap"><table><thead><tr><th>الفريق</th><th>المشرفة</th><th>الموظفات</th><th>Quality</th><th>C-SAT</th><th>FCR</th><th>AHT</th><th>Utilization</th></tr></thead><tbody>${rows}</tbody><tfoot><tr><th>الإجمالي</th><th>8 مشرفات</th><th>106</th><th class="green">90%</th><th class="green">91%</th><th class="amber">85%</th><th class="green">3:28</th><th class="green">87%</th></tr></tfoot></table></div></section>`}
function superCards(){return `<section class="panel"><div class="section-head"><h2>السوبر والفرق التابعة</h2><span class="muted">وصول مستقل لكل مستوى</span></div><div class="supercards">${Object.values(SUPS).map(s=>`<div class="supercard"><span>سوبر</span><h3>${s.name}</h3><b>${s.total} موظفة</b><small>4 مشرفات • 4 فرق</small><a href="${s.name==='عهد'?'super.html':'#'}">فتح لوحة ${s.name} ←</a></div>`).join('')}</div></section>`}
function notes(){return `<div id="notes" class="lower"><div class="panel"><div class="section-head"><h3>الملاحظات التطويرية</h3><span class="link">عرض الكل</span></div><p class="notice red">انخفاض FCR في الفريق 2 <small>منذ 3 أيام</small></p><p class="notice green">تحسن الجودة في الفريق 4 <small>منذ 4 أيام</small></p><p class="notice red">ارتفاع AHT في الفريق 6 <small>منذ أسبوع</small></p></div><div class="panel" id="sessions"><div class="section-head"><h3>الجلسات والمواعيد</h3><button class="smallbtn" onclick="scheduleSession()">+ تحديد موعد جلسة</button></div><div id="sessionBox">${sessionView()}</div></div></div>`}
function sessionView(){const raw=localStorage.getItem('adaa_session');if(!raw)return '<p class="muted">لا توجد جلسة مجدولة حاليًا. حدد الموعد ليظهر المؤقت.</p>';let data;try{data=JSON.parse(raw)}catch{data={date:raw,type:'جلسة'}}const date=new Date(data.date);const shown=isNaN(date)?data.date:date.toLocaleString('ar-SA',{dateStyle:'full',timeStyle:'short'});return `<div class="sessionbox"><span class="session-type">${data.type||'جلسة'}</span><b>جلسة مجدولة</b><strong>${shown}</strong><div id="countdown" class="countdown">جاري حساب المؤقت...</div><button class="linkbtn" onclick="localStorage.removeItem('adaa_session');location.reload()">إلغاء الموعد</button></div>`}

function scheduleSession(){
 const old=document.getElementById('sessionModal');if(old)old.remove();
 const now=new Date();now.setMinutes(now.getMinutes()-now.getTimezoneOffset());
 const min=now.toISOString().slice(0,16);
 const modal=document.createElement('div');modal.id='sessionModal';modal.className='modal-backdrop';modal.innerHTML=`<div class="session-modal" dir="rtl"><button class="modal-close" id="cancelSession">×</button><h2>تحديد موعد الجلسة</h2><p>اختاري التاريخ والوقت من التقويم بدل الكتابة اليدوية.</p><label>نوع الجلسة</label><select id="sessionType"><option>Coaching</option><option>Side by Side</option><option>Monthly Review</option></select><label>التاريخ والوقت</label><input id="sessionDate" type="datetime-local" min="${min}"><div class="modal-actions"><button class="smallbtn" id="cancelSession2">إلغاء</button><button class="btn" id="saveSession">حفظ الموعد</button></div></div>`;
 document.body.appendChild(modal);
 document.getElementById('cancelSession').onclick=()=>modal.remove();document.getElementById('cancelSession2').onclick=()=>modal.remove();
 document.getElementById('saveSession').onclick=()=>{const dt=document.getElementById('sessionDate').value;if(!dt){alert('اختاري التاريخ والوقت أولاً');return}const type=document.getElementById('sessionType').value;localStorage.setItem('adaa_session',JSON.stringify({date:dt,type}));modal.remove();location.reload()};
}

function startCountdown(){const el=document.getElementById('countdown');if(!el)return;const tick=()=>{const raw=localStorage.getItem('adaa_session');let data;try{data=JSON.parse(raw)}catch{data={date:raw}}const t=Date.parse(data.date);const diff=t-Date.now();if(diff<=0){el.textContent='🟢 الجلسة بدأت الآن';return}const d=Math.floor(diff/86400000),h=Math.floor(diff%86400000/3600000),m=Math.floor(diff%3600000/60000),s=Math.floor(diff%60000/1000);el.textContent=`متبقي ${d} يوم • ${h} ساعة • ${m} دقيقة • ${s} ثانية`};tick();setInterval(tick,1000)}
function managerHome(){shell(`<div class="hero"><div><h2>مرحبًا شهد 👋</h2><p>إدارة المشروع بالكامل من لوحة واحدة، مع وصول مستقل لكل سوبر وفريق.</p></div><div class="heroquote">106 موظفة • 2 سوبر • 8 فرق</div></div>${periodBar()}<div class="summary"><div><span>إجمالي الموظفات</span><b>106</b></div><div><span>عدد السوبر</span><b>2</b></div><div><span>عدد المشرفات</span><b>8</b></div><div><span>متوسط الأداء</span><b class="green">89%</b></div></div>${structure()}${superCards()}${kpis()}${charts()}${teamTable()}${notes()}`,'manager','شهد','إدارة المشروع')}
function superHome(){const s=SUPS.عهد;const cards=s.teams.map(t=>`<div class="teamcard"><span class="statusdot green">●</span><b>${t[0]}</b><span>مشرفة ${t[1]}</span><strong>${t[2]} موظفة</strong><a href="#teams">فتح أداء الفريق ←</a></div>`).join('');shell(`<div class="hero"><div><h2>مرحبًا عهد 👋</h2><p>متابعة فرقك الأربعة بشكل مستقل مع الإجمالي.</p></div><div class="heroquote">53 موظفة • 4 فرق • 4 مشرفات</div></div>${periodBar()}<div class="summary"><div><span>إجمالي الموظفات</span><b>53</b></div><div><span>عدد المشرفات</span><b>4</b></div><div><span>عدد الفرق</span><b>4</b></div><div><span>متوسط الأداء</span><b class="green">89%</b></div></div><section class="panel"><div class="section-head"><h2>فرق عهد</h2><span class="muted">اختر فريقًا للتفاصيل</span></div><div class="teamcards">${cards}</div></section>${kpis('super')} ${charts()}${teamTable(s.teams)}${notes()}`,'super','عهد','لوحة السوبر عهد')}
function supervisorHome(){const t=SUPS.عهد.teams[0];shell(`<div class="hero"><div><h2>مرحبًا وجدان 👋</h2><p>لوحتك الخاصة كمشرفة — فريقك وموظفاتك فقط.</p></div><div class="heroquote">${t[2]} موظفة • فريق 1</div></div>${periodBar()}<div class="summary"><div><span>موظفات الفريق</span><b>${t[2]}</b></div><div><span>متوسط الأداء</span><b class="green">90%</b></div><div><span>جلسات هذا الشهر</span><b>6</b></div><div><span>تحتاج متابعة</span><b class="red">2</b></div></div>${kpis('team')} ${charts()}${teamTable([t])}${notes()}<section class="panel"><div class="section-head"><h3>موظفات وجدان</h3><button class="smallbtn" onclick="window.print()">طباعة تقرير الفريق</button></div><div class="employeechips">${EMP.slice(0,7).map(e=>`<span>${e.name}<b class="${cls(e.score)}">${e.score}%</b></span>`).join('')}</div></section>`,'supervisor','وجدان','لوحة المشرفة وجدان')}
function employeeHome(){const e=EMP[0];document.body.innerHTML=header('employee','سارة أحمد')+menu('employee')+`<div class="app"><main class="content"><div class="page-title"><div><h1>مرحبًا سارة أحمد 👋</h1><p>مساحتك الشخصية لمتابعة أدائك وتطورك.</p></div><span class="pill excellent">أداء ممتاز</span></div>${periodBar()}<div class="summary"><div><span>أدائي الحالي</span><b class="green">${e.score}%</b></div><div><span>Quality</span><b class="green">${e.quality}%</b></div><div><span>C-SAT</span><b class="green">${e.csat}%</b></div><div><span>FCR</span><b class="green">${e.fcr}%</b></div></div><section id="performance" class="section"><div class="section-head"><h2>مؤشرات أدائي</h2><span class="filter selected-period">شهري</span></div><div class="metrics">${metricCard('AHT',e.aht,'الهدف 3:30',ahtGood(e.aht),'down')}${metricCard('Absenteeism',e.abs+'%','الهدف 95%',e.abs>=95)}${metricCard('Quality',e.quality+'%','الهدف 80%',e.quality>=80)}${metricCard('Utilization',e.util+'%','الهدف 85%',e.util>=85)}${metricCard('C-SAT',e.csat+'%','رضا العميل',e.csat>=90)}${metricCard('FCR',e.fcr+'%','من أول مكالمة',e.fcr>=90)}</div></section><div class="lower"><div class="panel"><h3>نقاط القوة</h3><p>أداء متميز في الجودة ورضا العميل وخدمة العميل من أول مكالمة.</p></div><div class="panel"><h3>فرص التحسين</h3><p>المحافظة على النتائج ومتابعة المؤشرات بشكل مستمر.</p></div></div><div id="sessions" class="panel"><div class="section-head"><h3>الجلسات والمواعيد</h3><button class="smallbtn" onclick="scheduleSession()">تحديد موعد الجلسة</button></div><div id="sessionBox">${sessionView()}</div></div><section class="panel"><div class="section-head"><h3>تقارير أدائي</h3><button class="btn" onclick="window.print()">طباعة التقرير</button></div><p>متاح أسبوعيًا، شهريًا، ربع سنويًا وسنويًا حسب الفترة المختارة.</p></section><footer>منصة أداء • ملف الموظفة سارة أحمد</footer></main></div>`;bindMenu();bindPeriods();startCountdown()}
function reports(role){const cfg={manager:['شهد','تقرير شامل للمشروع وجميع السوبر والمشرفات والفرق.'],super:['عهد','تقرير السوبر والفرق الأربعة التابعة لها.'],supervisor:['وجدان','تقرير فريق وجدان والموظفات التابعة لها.']};const [name,desc]=cfg[role]||cfg.supervisor;const teams=role==='manager'?ALLTEAMS:role==='super'?SUPS.عهد.teams:[SUPS.عهد.teams[0]];shell(`<div class="hero"><div><h2>التقارير والتحليلات</h2><p>${desc}</p></div><button class="btn" onclick="window.print()">🖨 طباعة التقرير</button></div>${periodBar()}<div class="reportcards"><div><b>أسبوعي</b><span class="green" data-report-score="0">88%</span></div><div><b>شهري</b><span class="green" data-report-score="1">90%</span></div><div><b>ربع سنوي</b><span class="green" data-report-score="2">94%</span></div><div><b>سنوي</b><span class="amber" data-report-score="3">89%</span></div></div><section class="panel tablepanel"><div class="section-head"><h2>مقارنة الأداء حسب الفريق</h2><span>SL • NPS • Quality • C-SAT • FCR • AHT • Utilization • Absenteeism</span></div><div class="tablewrap"><table><thead><tr><th>الفريق</th><th>المشرفة</th><th>الموظفات</th><th>الربع الحالي</th><th>الربع السابق</th><th>الاتجاه</th></tr></thead><tbody>${teams.map((t,i)=>`<tr><td>${t[0]}</td><td>${t[1]}</td><td>${t[2]}</td><td class="green" data-report-score="${i%8}">${REPORT_DATA['شهري'][i%8]}%</td><td class="amber">${[89,88,91,86,89,84,90,85][i%8]}%</td><td class="green">↑ تحسن</td></tr>`).join('')}</tbody><tfoot><tr><th>الإجمالي</th><th>${role==='manager'?'8 مشرفات':role==='super'?'4 مشرفات':'1 مشرفة'}</th><th>${role==='manager'?106:role==='super'?53:14}</th><th class="green">91%</th><th class="amber">88%</th><th class="green">↑ +3%</th></tr></tfoot></table></div></section><section class="panel"><h3>تحليل مختصر</h3><p>تم إبراز المؤشرات المرتفعة باللون الأخضر والمنخفضة بالأحمر، مع مقارنة الفترات وإظهار الإجمالي في نهاية كل مستوى.</p></section>` ,role,name,'التقارير')}
function login(){document.body.innerHTML=`<div class="loginPage"><div class="loginCard"><div class="logoBig">أداء <span>Aadaa</span></div><h1>منصة أداء</h1><p>متابعة • تطوير • إنجاز</p><label>نوع الحساب</label><select id="role"><option value="manager">مدير المشروع — شهد</option><option value="super">سوبر — عهد</option><option value="supervisor">مشرفة — وجدان</option><option value="employee">موظفة — سارة أحمد</option></select><button class="btn" id="go">تسجيل الدخول</button></div></div>`;document.getElementById('go').onclick=()=>{const r=document.getElementById('role').value;location.href=r==='manager'?'manager.html':r==='super'?'super.html':r==='supervisor'?'supervisor.html':'employee-home.html'}}
function route(){const p=location.pathname.split('/').pop()||'index.html';if(p==='manager.html')managerHome();else if(p==='super.html')superHome();else if(p==='supervisor.html')supervisorHome();else if(p==='reports-manager.html')reports('manager');else if(p==='reports-super.html')reports('super');else if(p==='reports-supervisor.html')reports('supervisor');else if(p==='employee-home.html')employeeHome();else if(p==='index.html'||p==='')login();else login()}
document.addEventListener('DOMContentLoaded',()=>{route();setTimeout(startCountdown,300)});
